{
 "title": "Jetson Exporter",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "instance", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "CPU Usage per core",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort_desc(sort(tegrastats_cpu_percentage{instance=\"$instance\"}))",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "CPU Usage Total",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 10, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sort_desc(sort(tegrastats_cpu_percentage{instance=\"$instance\"}))",
     "legendFormat": "{{core}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "tegrastats_temperature_celsius{instance=\"$instance\"}",
     "legendFormat": "{{component}}"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "tegrastats_ram_megabytes{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  },
  {
   "title": "Swap",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 10, "x": 14, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "tegrastats_swap_megabytes{instance=\"$instance\"}",
     "legendFormat": "{{type}}"
    }
   ]
  }
 ]
}