#!/bin/sh
set -e
# Automatically added by dh_installsystemd/13.2
if [ -d /run/systemd/system ]; then
        systemctl --system daemon-reload >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installsystemd/13.2
if [ "$1" = "remove" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper mask 'jetsonexporter.service' >/dev/null || true
        fi
fi

if [ "$1" = "purge" ]; then
        if [ -x "/usr/bin/deb-systemd-helper" ]; then
                deb-systemd-helper purge 'jetsonexporter.service' >/dev/null || true
                deb-systemd-helper unmask 'jetsonexporter.service' >/dev/null || true
        fi
fi
# End automatically added section