name: test

on:
  workflow_call:

jobs:
  test:
    name: Run go test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run go test
        run: go test ./... -v